apiVersion: v1
kind: Secret
metadata:
    name: installconfig
    namespace: replace-me
    labels:
        cluster.open-cluster-management.io/backup: ""
data:
    install-config.yaml: ENC[AES256_GCM,data:CClhysZsqPMVlrDCpgOCvw0soeemt4Jx6+PQJQUy6c9oEUoxMCdSe7Lx1j7MIfg8tKGO3q1/HfHdoH89AF6mDsx6Ym570QuuMxpWiLyHcCCL0f2mxoK9QIcfzkjFLGpwDkedzV3hPUuSxfIzG22mom0r+xF/ISl94bVGiPu7YU17hnNMx/yrUicX59a45RDcPGF6BWq3ScNSvKGdfLJWwQtFG/P4ADFvW52IicCAQ/vg8VAMIv4B9jrtXvJ86FRIVeg6fCZDtkM3+6F/PmH9PXegHmfqQG9faiWnJbBE87I0VynYFhYxtTxJB60NB34QXerI5qcLsa5iKNimPd2PrPtKs4V7QfqNgX/k8pvnfK4IIVheI6ekXuaKWoQB6SssGIvYqifdnAcytP1NIdM9jVfA6uy/+0LXmmk6sDkcwHc2N26glwadcU8cwumBCPc7Oceh++e4WzFxeYrBVoKmDqZuwygt0Shy5AiF6/Id2yONCqvJ+tqnyLo3nXl+WHaZjyU0f8ksvIZbUfa08hYlMlB4mZ8GrWQhTqPcCKqegyNOy6nUQ9dLJqRitj5zltZQBPgNMtJaFCdrQNV0PuQQkcZF+Jq6jc1eEQSyTj5ZJVR5SR/S2aDHpOiImQpg5D8B5T5bfvHZ2FnO8a77tLny/SJqOCRxLFlms6BUsecB9xurQgkomgxurkuzto6PURV3BN3ESE3jsxU7+uzkBlfdLSn5h0kJ9C8IW5X3dFXD2j2iKZk9GNFrCbCZyUJUhPImNrIKowGzsO4nyB7NtJrE+YJ7Eop1ESNEAGMQw9kyIKo46xavkB+2IDu4/zUiNAzNjSj6okdtcZUJzxYSb3G1l5CCkktVuOYJ4ihV6FqhfK+29WOvmHRIAx2PBqBAEY4MPxqdfG0mjNPMgYtIpAxqxcb+OOTSJXTNRAKBlpz/EYnFGycRxJAlrXBgZZ8g2BYV/JybXuG3W5A5xpu9pBhqY8TpKqZ2pYbKP6wGUS71EAKnf7swbqD/FQR2/uv2oPBf32nxhYGgv70ENJKn3GoT4/qUPJWLWsILtwFvRfkcfCANe1WCYEMEwwQo+lQtgrqFdRXSzrE3B1oAicKNCulC9Ka1knig5RAN8ZPt4qiZ6uvGUIxhy+wLjpJFoPbtfIm8tQP2n/1urDjclTEJiG1YDDFTG9Vs5kroqwgwFBV2ICgqQRM1V0sd4VDTatrSW4CyL9cVnUVoIwz+2LgCPq0pmj+0X+R5GJWB8RayQlz19yd4zBS5IX3KnTTnU+W0w+C1D1YAhN6KYbVkSE8R3oQf1Ovsd8nLYwcvEQtQfNxt5AWdSWGFAehqEsEstIxc7ODP5l9IYRRItmzqPMQ9xjBADnCeAkT9flv6lgj4WYVvL3mhB/4Ua829L+y9w06p6JOBw7M/IF3/Sj/dUEId4vYCIdTHy22a7yadD0/EMcNZS4H5lH62Aei+IjAZa8u8bmeJ86FK1LHIeF/hMIAXrUQPmCos/XDcZD5n1c8xXvLopK65ob6aYTBFZL2oe/3/Nqpyfv7EEfstkqKgDuKicVay4sn48X1WwpwjXt88F666aWJ4Rk7TcKMjUT6i8Ir/4lBf2nWjHLqkttvX3SRMJTXZt+fdkuHt4iOEBGll3+eJ6m9R0Z1B0O3z1YprG5gxc5kj1wmJ5J8p2STPwxjuxI7gytu5v+/eoCGy14GhN7MZMbZu6a4yC9Muv1fMx0sFaUJuJYCi64nBQtuNnfgZ+cozLsWFoOyAKIgiChl9SVeKm3JlYA8mk5viDfvfsfJNYV4VxDNfBHjL4al2VEEo8h0kA7J0iS+OdfHbGzbGF7UaHW2XttN312GPQvO4pq6wm5aNV4/xNgVR3h6trKIwhNrU86F2hCguBVzh3sENKZkWBH0mWQuAvniG1kv74JWrFn1SuBfzGUwQr6XYlRKYZDtw+gL+fXsakpi9HWxy4B3ID/Cf8DBrbhW8AqLn93oqyu9pkjEL9ftH6l7dlxvyaef0WQ==,iv:UzuqYIY82FiNrfO1stuMLsr2r1UDyGQtls0cNUV0kkQ=,tag:Xlq/ur/jXVd7qW6s05LJAQ==,type:str]
sops:
    lastmodified: "2025-11-22T05:40:53Z"
    mac: ENC[AES256_GCM,data:na//Cb1g/EMFBOoKgrBYeMjZgWcOm8dLtENwLo7dFCcNiRR8hDk4zVcFYfKhAFMI+M6b+ClvrpGp0gfSVe/ESr7VVAco4ppu6FnwFFSfElPJuVYqZcGRgG+6A5e2PhM7O2N4PipsHXx8g8a2heaOSit7l8Fzs0svrNWfclimkoE=,iv:ooss05d/zrjSmPrG1yxT2vKniOiqdI5Mnc3FUgKdnUA=,tag:fsWd9I+FzjNzJqXBF6A2iw==,type:str]
    pgp:
        - created_at: "2025-11-22T05:40:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DeXeC3vKOE18SAQdA66uxB6ieY7dZCRAyNJl/ZmvoJqy7gpKRXUflJoVNxFww
            5ovobL7foLUis+LKnT89IpmsXWmONxNau/6HIbK+4nxjOSPOb6LLOnRpviMoY2rL
            0l4B2gI9Xw+3ERQP5sWyEWHjDnLCGAeaYEg4n2WBq7IyxNgf1k4VBaZ3lnb7Idnl
            Byx/KD5N+Fy8mhf1gl/0Sh0A684niZfbihVM7IT0cjVLLnLZPl35J3Ob0QVqWS16
            =hi53
            -----END PGP MESSAGE-----
          fp: 690EB362BCE71D5794727EF0382DB86937BB1D2F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
