apiVersion: v1
kind: Secret
metadata:
    name: installconfig
    namespace: replace-me
    labels:
        cluster.open-cluster-management.io/backup: ""
data:
    install-config.yaml: ENC[AES256_GCM,data:xoaMfdbsgxlk9+QfO3cSGUakZyc2IMib8+3lOzrHtg4e5Ofo8N9RsC/kkTm+evWFLdNb4LyXQtOCbQ/ZSLp/9A/gPq7jdf/qFVhsAavutHCV5gB3I9o1cIVm6f99HnqR/r5ONGbi4SzPEb5rLSp3W0p8VdrmlwfBaLgXrPQN1RS+74l+FO4aw7xET9B1o23ITHJQ6w8mWQ7fE394EPRWxyZehMbeqhmAx48a1RC7qVMV9NH2yw/ioAJgr1VY/77w4HVeVmliHq3+IIc33lcaS/JH0qMzOeDovT20Eq52nldFECLMe7N+qKcLNL8nagIlfn6cOhkzqxWQg136DVS8XHNtPUn+6XlC295fZqItPiKHGNbhCaLSflYlFzHY0oAFNiA8QFOW1ZdYY5DvY26x3Tuu3Rgmoofunn+Mp+vPzNTaTU8R7l+tPwP0JbRvY+Mbzcml1eA+2vzLg4szRL1D/exDzo6Kp1uFeR9KMuoGsqosHgZhLLGNLY6IjoZNcahIy/S1Udivu7iUI0A8KatwplwIrrGi1FL8V70tnI6AHZxtAAgvau8AYd8BIdLXXvnGNi3U9Sc4KoawozG2w6jjp8x0BBu8XAkFFJqqB3tQQya73BtKxgKp5ty8kzyiRw3B0RMYP3kQyosC90qwXDNUtZsWtAMYquct7KbUqxxz5bdoro8XMd5R8Tz/uzFFeDQx12zHz4U05yUuy088v0e96/gCrFVZU9ySbt8OucPLsLEDGMwhZF8UYdKEVeIBUTEYmdAUgmnLZTYF00wSYGp2pQxLdg36tGW8edlVlS9WhSQWBcDCoL7uL3L8oEpmBguP6r77UZbinx56yXQsWiFzJx8jay2BVUWBznib+r9EgZJK5hAtbgBJPSEvnAqAQMXah0W0TkeLXVERYHfXAyCoA6FUNv3GOHzKlyX/b9QbQN8yIpf+YswprlJwuLgU+Sp2USP7JklirPBznnAdT/Wia00IU+YkDNo9L4AsjSFPvRI/mLvC1jUJdxiEeDa3HJPgcygcXOneUZO42q/9iP1mFHZQ+cKP6/GIv9aErjKc6C680nIa0DbpBPkRwfu6jANjRSSkjdzsQRsukGLnvJpbTtwycLr7DsNCDneStvxo1/V8fkMrgymsO5ExBVTmOl2R8Krmp7yDFx5W0MCAHpNrFhRQeoY8/Npj3a/2LHMjYi9beW+y7XV57LDPwPm3GyJtuV4eGf0YwGNyXqLPXxVY7eT0IIY9q93xgWHkS7INTQN1D02h6C05b/HrNXgjBJqtZDRN5hFxTL5vQwFcxESrhxoqYWTgT1lbFUULKrUFJvIKS34V6lKIyZnPCp1sC8dlReP20XxBgqb58/yv+WZKUmbjR4RDp1FF8dbTa3325JjjJcDx3vx2bFQ5z/doH1W2rOe0/eQJFKClWhBzIIsBIfdadwcs1vabTTwlw+K2fkFAPFwDxm1KqnsUKxCgXD277qxnX2k0ZHRS9TFjoEt6kWxH7QoK4CewrnXg82zbKhgkoO1DfaicqconDxOBqX/d1Y6iwRhu4scJq3vlLSkwX4mvlMZ2j2vGvxBzLyXlZDaMDvhJyLPhDQPpEqHEKzAWAsWJggUSi9/cleRgBYHsPLP60OJhvV+fZW5DhBhbyuKr5B42ip90H8YOElmR/Si6LtKYJFgovi75Su5gfqDRq9SHmRm5i5KD10YS26bB25tw96H/bnieBQpUZ/OPysvm9WOYtWHnvoDZrEI+pBnZywzHK0h9kp6W7cyR3dFjwUvM0lp2507mWnXDWzWlj0O5GxU9ZAbrjgo53Arkv3AfRqSFjM6UbgrAHrIJ7gu+F8arD1x/rEsadL+YnwQhhOWEUgmMZeotHLC/8yhuQkbrKFrS1G47bbWFDnKUgn5OLcxM615JUDKHsV/JHeu8iFWqLY6Sh6hH3w1prCgNXxTPTcnsb4i2YSCrNPiNzC4sZzqFm0orE6T8uDEzMhuEuJpvq34CyUkxpRXnwIbkKO4Djg==,iv:m7aDEgPBUVBQ1gxClzBe8Peyt7sik86whu07AdI05Hk=,tag:TOpMoq2h8lbcT9Jv5nPOPA==,type:str]
sops:
    lastmodified: "2025-11-24T19:45:01Z"
    mac: ENC[AES256_GCM,data:lYh84qHyE5tJd9+7WlK5T3eox/YuXKGZgWGNJWhLBCbOF7yDdAN7GEUKBd4AsokVlUOM8MhbEW6hWW/dWIQMn5QBdtTOS+ALO/8AaQxdwPUUGn4X2wjDKyBNyyISS9qMyuLg5ATfjJjYNgAhHE57v0jAl49ecrWAR5LeICAR5DE=,iv:Kyn5S2AHUcNM2MP+lIiyAxj4lx/oxNdaEFdkHOJhfhM=,tag:7hWM84a5/V/tcZuysB8Ibg==,type:str]
    pgp:
        - created_at: "2025-11-22T05:40:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DeXeC3vKOE18SAQdA66uxB6ieY7dZCRAyNJl/ZmvoJqy7gpKRXUflJoVNxFww
            5ovobL7foLUis+LKnT89IpmsXWmONxNau/6HIbK+4nxjOSPOb6LLOnRpviMoY2rL
            0l4B2gI9Xw+3ERQP5sWyEWHjDnLCGAeaYEg4n2WBq7IyxNgf1k4VBaZ3lnb7Idnl
            Byx/KD5N+Fy8mhf1gl/0Sh0A684niZfbihVM7IT0cjVLLnLZPl35J3Ob0QVqWS16
            =hi53
            -----END PGP MESSAGE-----
          fp: 690EB362BCE71D5794727EF0382DB86937BB1D2F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
