apiVersion: v1
kind: Secret
metadata:
    name: installconfig
    namespace: replace-me
    labels:
        cluster.open-cluster-management.io/backup: ""
data:
    install-config.yaml: ENC[AES256_GCM,data:dUFMnp8H3swLpqs1af+pUVFJgXEinNmkBdMAqEGpQjwF4qBpcKPNdvZ4iKZ5lu7vZwOsRA+O/6W4NrH2z7nvrh0Ly5JGSi7V6QEfLrVqjuoaFWvX06pd44wvJumf1+cIHVZEGvJZoVBQ8ULY9ELxFFZK09cg+Z7xH1pMOn626of9Ii6pK1PERr7qWQp2ZVJ2k0Ik61WmQ1VWh+VUsEdyj19Yuyv/YzdYxDMg0Ry3r9sRyUtixpBut+pmtKxF2+ZHNPVZTChbyDaMrN/BsG/Hju1dRHYPywyrGH7G6m1n+Ebk8/+IaSeBl+Jpd8Xllr27qRMuZCy71rplSwEYtkBh2RsxVPPedoIq9Bs7PgVywj7HHcWWKqOF9pUWpaJ3fCX/Xgdwa6xouShVhJ422ApU16JBzSDjhAecqsJqgqydXy8Zi4OgEvEHZxDaEZF/jbb2Bo4QvorTv3PxNnvOF8Nt9fG2GiwdXKF//Wi2//ITNwjRanUjCovutHdSYBMrYH34hPJ5wgUPT3flsxfDTdcuT0QPf4bgzstiB68TKv88DMhI5SnQNM1WU6cZwWfn9E0p7j321g6K9qJVfhgYMpriy50VseDpereRsFqvgRqa6mC9+FaSyxvkSoGCk3l8jyWdtA5SDyRMXjWqtZsPRNlGZBnHE4fVG6P6/1aAYcHbuq6bXmfySQt717kBfoNE5f4i6DrRW4Vm/XtsRIE1FHsd7ikE5G5NcxaPNj+OjxT+4+x5DfLSvFMe/1yTrdBBz5Kd3bjFQ4HvQMLIZP7cQLlJ4hgdVkEDL0jmQ0ynlMIfTzoNUpOp1engW3U8twdXeORo4A0VQZO8Kt8hc1zyzAkbNBwW9ceN3lLDQKbz3EdOorYcdfuMgM3LX1hzgtptSLvqJ24kY3vbOtBAf6ffPUZSkPbU5+jby22IghpXcKl613cEg7gy2LCKt0dR5mlFxPO6iZKzJA/Ur4Nosjim7XIZ3DkT4KTBXQna8lvxDX6TgPrK3d0qJOtlaZKAAJgkwkh8nPk++3pw6fj3EGvUiMHwQx7iTikOr4faxrVIi2cKn2gvLtxaWOui/whjEbXLx0+L+qv9CqUgeCLMUqac8zaACG4zuXCNYrp3T4Q2Qhw4TTxU5Tz1qzS1CX9d9jpZbd02zxNQHTPXHunfhuk8Ya51dC7i1Wy2qXBJIGXt0L2HykdnER1VDK3GCE3WzoiojWu/i3d30b57m6OtF39jrwOBLPJjVoMrlGmyaK0WdL+t3Lf/WxCQ8RZv6tF66FAHeYaT/tLgkEDRwzh4+nNwPiZJV7jixF0SeeYXvuHZ8Hr4cytsFkc9qJZE4P31jK5ftfMa4tx9VnERhf57Kw9jAcHh24rS1C/+dUst5PNbZFO1+Q5RwcsPNPLUjy1JTJvfjfVObOJH48cY7v9FY9rCFQpGcniRr9YSjqD7Px6Z5rNJ39D7juHfLYOAazL/p4D35kDCS+Wy+QvbtmUf4AtqMl4pQiGvrVouJjVZgwQmRLwmNTBJT4Pb/OBshh5pTrIZn4/QVOkV64EwrF1piReRtVWeMA3k9+2SluZkJDwb6fNovD2t9OPDdtWam7hZN5ERRgaSY74W12PG0hMdFA2zkqvOipeDnEbXJUDH1rogkwSDAOkRvCJDauO/DE10gtsTFukCRTIobP+Z+SHjp2RkgId0SBsHKyKsMb0veJ0jU1yv0cD6RWH/vSXaOPAdlm/xBaVb5dU1VMkI4sQ2dJkCRGbNAqkZa9mwGjCzJZksldSYDLBtkRLwrm6AnfBCq+vaS/tdId53P87vxCQvVaWDrZpXoLORbv7IyvIo7AlWH++Oer4+eVuvGBq8mCov95WFG4N9tNltEOQpA2tNSJmiHBuCypJxQdFryOqS2oithm1Q/gDJ1U20ZRuPe0vu25D/BAzunxLrVQgeXG8FEFPrrvTTMnMIas7tbMCa5jplbO0jAgQ1YbQJAQWwJ0c7g9KW9lkmajEe2A==,iv:G2OlfVyoSmIYWA0oQy21BDaukzpg16UErZXaJEbB7xc=,tag:udNwhUW17+whpKaApaIhiQ==,type:str]
sops:
    lastmodified: "2026-03-26T20:06:02Z"
    mac: ENC[AES256_GCM,data:nBpZ3tjiKnYDyWZ8sPUDbUUy7EORSTzgi1MRl6UIeqfIuqA5UAKQMKMdbo0Omc85ZHz5kyU3nsWOo5UHaT64igCVAQNFSNoB2/L+xBlNozunFZCSO8dqREfN9OLFK9+KAC8cxsz7wiXjW3tkPoh7jeDXY1ur+/4EK8O6RPhQYyI=,iv:bWySsuGZhsA/Jz1Frw3r8GKGA4zWjz06SLWE4Hz0N/M=,tag:GE/PWq6WfsxU7LyQ5ArRgQ==,type:str]
    pgp:
        - created_at: "2026-03-26T20:06:02Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DtVMEJohTtwUSAQdA5xkehF23vrgTMJoYUVxmwHkmWy12n0mURm+Cgi5SSyIw
            s1ZXulWUqHDQkPyv/JIY2oPKhvut+KJZIpvUfFyRwG7Rj+u74FEc6UPzjhhCvLBC
            0l4BTrm2ANg/iOcERDIh9kdrdnblri8DM6jSWpihSm/jl+Bez0pOpu2wyLGlaFJQ
            susjc7edAAxqJ7g0sigdZ3NS4OOPRlR1auvbMZvGhwDRrQ0fFIuB2ujJ1RvzL7SC
            =2Smx
            -----END PGP MESSAGE-----
          fp: 6FD445DC1FB700FBE7A7ECC544CD8DE2673D3065
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
