apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: installconfig-secrets-generator
  annotations:
    kustomize.config.k8s.io/behavior: merge
files:
  - ../../../../../../secrets/installconfigs/aws/installconfig.yaml
