apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: pull-secret-secrets-generator
  annotations:
    kustomize.config.k8s.io/behavior: merge
files:
  - ../../../../../../secrets/pull_secret.yaml






