apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets/portworx
  - ../../../../components/resources/portworx/storagecluster/aws
  - ../../../../components/resources/portworx/migrationschedule
patches:
  - target:
      kind: StorageCluster
      name: replace-me
      namespace: portworx
    patch: |-
      - op: replace
        path: /metadata/name
        value: aws-sc
  - target:
      kind: MigrationSchedule
      name: change-me
      namespace: portworx
    patch: |-
      - op: replace
        path: /metadata/name
        value: example-todo-app
      - op: replace
        path: /metadata/name
        value: example-todo-app
      - op: replace
        path: /spec/template/spec/namespaces
        value:
          - example-todo-app
