apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../components/resources/portworx/storagecluster/aws
  - ../../../../components/resources/cockroachdb-insecure
generators:
  - ./credentials_generator.yaml
patches:
  - target:
      kind: CrdbCluster
      name: crdb-cluster
      namespace: cockroachdb
    patch: |-
      - op: replace
        path: /spec/regions
        value:
          - code: us-east-1
            nodes: 3
            cloudProvider: aws
            namespace: cockroachdb
  - target:
      kind: StorageCluster
      name: replace-me
      namespace: portworx
    patch: |-
      - op: replace
        path: /metadata/name
        value: aws-sc
  - target:
      kind: Secret
      name: cloud-creds
      namespace: replace-me
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: portworx
