apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../../../../infra/components/resources/argocd/cluster
patches:
    - target:
        kind: ClusterRoleBinding
        name: argo-admin
      patch: |-
        - op: replace
          path: /metadata/name
          value: argo-admin-aws
    - target:
        kind: GitOpsCluster
        name: replace-me
        namespace: openshift-gitops
      patch: |-
        - op: replace
          path: /metadata/name
          value: gitops-cluster-aws
        - op: replace
          path: /spec/placementRef/name
          value: aws-gitops-placement
    - target:
        kind: Namespace
        name: replace-me
      patch: |-
        - op: replace
          path: /metadata/name
          value: gitops-clusters
