---
creation_rules:
  - path_regex: 'config.yaml$'
    pgp: D6E209161D562BBE3E8D032BD6C95688D40596F9
    encrypted_comment_regex: '^[ ]{0,}encrypted$'
  - path_regex: 'infra/secrets/.*.yaml$'
    pgp: D6E209161D562BBE3E8D032BD6C95688D40596F9
    encrypted_regex: '^(data|stringData)$'
