---
creation_rules:
  - path_regex: 'config.yaml$'
    pgp: 6FD445DC1FB700FBE7A7ECC544CD8DE2673D3065
    encrypted_comment_regex: '^[ ]{0,}encrypted$'
  - path_regex: 'infra/secrets/.*.yaml$'
    pgp: 6FD445DC1FB700FBE7A7ECC544CD8DE2673D3065
    encrypted_regex: '^(data|stringData)$'
