---
- name: Deploy demo environments
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - set_fact:
        primary_environment: "{{ environments | selectattr('acm_config.role', 'equalto', 'primary') | first }}"
        backup_environment: "{{ environments | selectattr('acm_config.role', 'equalto', 'backup') | first }}"

    - include_tasks: tasks/preflight_checks.yaml
      loop: "{{ environments }}"
      loop_control:
        loop_var: env

    - include_tasks: tasks/create_backup_s3_bucket.yaml
      vars:
        settings: "{{ common.dataprotection.settings }}"

    - include_tasks: tasks/install_fluxcd.yaml
      loop: "{{ environments }}"
      loop_control:
        loop_var: env

    - include_tasks: tasks/create_flux_subscription.yaml
      loop: "{{ environments }}"
      loop_control:
        loop_var: env

    - include_tasks: tasks/wait_until_managed_clusters_ready.yaml
      vars:
        env: "{{ primary_environment }}"

    - include_tasks: tasks/modify_managed_cluster_security_groups.yaml

    - include_tasks: tasks/create_px_async_cluster_pair.yaml
      vars:
        env: "{{ primary_environment }}"

    - include_tasks: tasks/finalize_app_deployment.yaml
      vars:
        env: "{{ primary_environment }}"
        app_name: example-todo-app
        app_namespace: example-todo-app
        failover_role: primary
