---
- name: Perform failover
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - set_fact:
        primary_environment: "{{ environments | selectattr('acm_config.role', 'equalto', 'primary') | first }}"
        backup_environment: "{{ environments | selectattr('acm_config.role', 'equalto', 'backup') | first }}"
        bootstrapper: "{{ common.bootstrap.bootstrapper | lower }}"


    # Manually stop the primary ACM hub and the managed cluster in AWS.
    # Since they are in the same region, this is more-or-less the same as
    # simulating a regional outage.
    - name: Wait for primary environment to become unavailable
      include_tasks: tasks/wait_until_unavailable.yaml
      vars:
        env: "{{ primary_environment }}"

#    - name: Pause all Flux kustomizations in the backup ACM hub
#      when: boostrapper == 'flux'
#      shell: |-
#        echo "{{ backup_environment.cluster.kubeconfig }}" > /tmp/kubeconfig
#        oc --kubeconfig=/tmp/kubeconfig get -n flux-system kustomization -o name |
#          grep -v cluster-config |
#          xargs -I {} oc --kubeconfig=/tmp/kubeconfig patch \
#            -n flux-system {} \
#            --type merge \
#            --patch '{"spec":{"suspend":true}}'
#        rc=$?
#        rm /tmp/kubeconfig
#        exit $rc

    - name: Failover Portworx volumes
      debug:
        msg: "todo"

    - name: Scale up the CockroachDB StatefulSet (which was scaled down by Portworx)
      debug:
          msg: "todo"

    - name: Kick off an ACM Restore
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ backup_environment.cluster.kubeconfig }}"
        definition:
          apiVersion: cluster.open-cluster-management.io/v1beta1
          kind: Restore
          metadata:
            name: "acm-restore-{{ lookup('community.general.random_string', length=12, special=false, upper=false) }}"
#            name: "acm-restore-test"
            namespace: open-cluster-management-backup
          spec:
            restoreSyncInterval: 1m
            cleanupBeforeRestore: CleanupRestored
            veleroManagedClustersBackupName: latest
            veleroResourcesBackupName: latest
            veleroCredentialsBackupName: latest

    - name: Wait for managed clusters to come back up again
      include_tasks: tasks/wait_until_managed_cluster_ready.yaml
      vars:
        acm_hub_env: "{{ backup_environment }}"
        cloud: "{{ item }}"
        wait_timeout_secs: 600
      loop: "{{ environments | map(attribute='name') }}"

    - name: Gather managed cluster kubeconfigs
      include_tasks: tasks/_get_managed_cluster_kubeconfig.yaml
      register: kubeconfigs
      vars:
        acm_hub_env: "{{ backup_environment }}"
        cloud: gcp

    - name: Bail if a managed cluster kubeconfig is missing
      fail:
        msg: "Managed cluster kubeconfig not found for '{{ item }}'"
      when: vars['managed_cluster_kubeconfig_' + item] is not defined
      loop:
        - gcp

    - name: Scale app replicas back up (if needed)
      debug:
        msg: "todo"

    # WARNING: DO NOT DO THIS IN PRODUCTION!
    # (You will make ALL of your users admins of your ArgoCD cluster!)
    - name: "[HACK] Add system:authenticated to argocd-rbac-cm Argo RBAC policy (Dex workaround)"
      debug:
        msg: "todo"

    - name: Update app DNS records
      include_tasks: tasks/finalize_app_deployment.yaml
      vars:
        env: "{{ backup_environment }}"
        app_name: example-todo-app
        app_namespace: example-todo-app
        overwrite: true
