# See this example for patching guidance:
# https://github.com/cockroachdb/cockroach-operator/blob/master/examples/3-nodes-insecure.yaml
apiVersion: crdb.cockroachlabs.com/v1alpha1
kind: CrdbCluster
metadata:
  name: crdb-cluster
  namespace: cockroachdb
spec:
  nodes: 3
  image:
    name: cockroachdb/cockroach:v25.3.4
  dataStore:
    pvc:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        volumeMode: Filesystem
  topology:
    zones: [] # patch-me
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: DoNotSchedule
  grpcPort: 26258
  sqlPort: 26257
  httpPort: 8080
