apiVersion: batch/v1
kind: Job
metadata:
  name: crdb-create-database
  namespace: change-me
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - image: cockroachdb/cockroach:v25.3.4
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: password
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: port
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: database
          name: do-it
          command:
            - ./cockroach
            - sql
            - --host
            - "$(DB_HOST)"
            - --port
            - "$(DB_PORT}"
            - -e
            - "CREATE DATABASE IF NOT EXISTS $(DB_NAME);"
