apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../../../apps/todo-app
  - ../../../../../../components/resources/cockroachdb/admin_tasks/create_database
  - ../../../../../../components/resources/cockroachdb/admin_tasks/create_db_user
generators:
  - ./credentials_generator.yaml
patches:
  - target:
      kind: Secret
      name: db-creds
      namespace: replace-me
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: example-todo-app
  - target:
      kind: Job
      name: crdb-create-datbaase
      namespace: change-me
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: example-todo-app
  - target:
      kind: Job
      name: crdb-create-db-user
      namespace: change-me
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: example-todo-app
