---
- name: "[{{ env.name }}] Checking for package '{{ item.name }}' in source '{{ item.catalog }}'"
  kubernetes.core.k8s_info:
    kubeconfig: "{{ env.cluster.kubeconfig }}"
    api_version: packages.operators.coreos.com/v1
    kind: packagemanifest
    label_selectors:
      - "catalog: {{ item.catalog }}"
  register: result

- fail:
    msg: "'{{ item.name }}' is not available in catalog '{{ item.catalog }}'"
  when: |-
    result.resources is not defined or
    result.resources | length == 0 or
    result.resources | selectattr('metadata.name', 'equalto', item.name) | length == 0
