---
- set_fact:
    ns: "managed-cluster-{{ cloud }}"

- name: "[{{ ns }}] Get the managed cluster's kubeconfig"
  register: data
  kubernetes.core.k8s_info:
    kubeconfig: "{{ acm_hub_env.cluster.kubeconfig }}"
    kind: Secret
    namespace: "{{ ns }}"
    label_selectors:
      - hive.openshift.io/secret-type = kubeconfig

- set_fact:
    "managed_cluster_kubeconfig_{{ cloud }}": "{{ data.resources[0].data.kubeconfig | b64decode | from_yaml }}"
  when: data.resources is defined
