---
- name: Check Portworx API endpoint availability
  include_tasks: tasks/_confirm_px_api_endpoints_available.yaml
  loop:
    - "{{ source }}"
    - "{{ destination }}"

- fail:
    msg: No Portworx endpoints are available in cloud '{{ item.cloud }}'. Check the StorageCluster for initialization errors.
  when: vars['api_endpoints_ready_' + item.cloud] is not defined or vars['api_endpoints_ready_' + item.cloud] | int == 0
  loop:
    - "{{ source }}"
    - "{{ destination }}"

- name: Create cluster pair
  block:
    - set_fact:
        vol_name: px-cluster-pair-secrets
        px_stork_image: docker.io/openstorage/stork:25.4.1

    - name: Create secrets container vol
      shell: "$CONTAINER_BIN volume create {{ vol_name }}"

    - name: Write cluster kubeconfigs to container vol
      shell: |-
        echo "{{ item.kubeconfig | b64encode }}" |
          base64 -d |
          $CONTAINER_BIN run --rm -i -v "{{ vol_name }}:/secrets" docker.io/bash:5 -c 'cat - > /secrets/{{ item.file_name }}_kubeconfig'
      loop:
        - file_name: src
          kubeconfig: "{{ source.kubeconfig }}"
        - file_name: dst
          kubeconfig: "{{ destination.kubeconfig }}"
    - name: Generate Portworx cluster pair
      shell: |-
        $CONTAINER_BIN run --rm --platform=linux/amd64 \
          -e KUBECONFIG=/secrets/src_kubeconfig \
          --name px-create-cluster-pair \
          --entrypoint /storkctl/linux/storkctl \
          -v "{{ vol_name }}:/secrets" \
          {{ px_stork_image }} create clusterpair cluster-pair-aws-gcp \
            --namespace portworx \
            --src-kube-file /secrets/src_kubeconfig \
            --dest-kube-file /secrets/dst_kubeconfig \
            --provider s3 \
            --s3-endpoint "{{ common.datareplication.settings.object_store.endpoint_url }}" \
            --s3-access-key "{{ common.datareplication.settings.object_store.access_key_id }}" \
            --s3-secret-key "{{ common.datareplication.settings.object_store.secret_access_key }}" \
            --s3-region "{{ common.datareplication.settings.object_store.region }}" \
            --v=9

    - name: Mark that cluster pair has been created successfully
      set_fact:
        cluster_pair_created: true
  rescue:
    - name: Remove secrets container vol
      shell: "$CONTAINER_BIN volume rm -f {{ vol_name }}"
