---
- set_fact:
    failover_role: "{{ env.acm_config.role }}"
    cloud: "{{ env.name }}"
    managed_cluster_kubeconfig: "{{ vars['managed_cluster_kubeconfig_' + env.name'] }}"

- name: "[failover_role: {{ failover_role }}, cloud: {{ cloud }}] Gather cluster hostnames"
  include_tasks: tasks/_get_cluster_hostname.yaml
  vars:
    cloud: "{{ cloud }}"

- fail:
    msg: "Couldn't retrieve the default hostname for the ACM hub in cloud '{{ cloud }}'"
  when: vars['{{ cloud }}_cluster_hostname'] is not defined

- set_fact:
    managed_cluster_kubeconfig: "{{ vars['managed_cluster_kubeconfig_' + cloud] }}"
    cluster_hostname: "{{ vars[cloud + '_cluster_hostname'] }}"

- set_fact:
    record_value: "{{ app_name }}-{{ app_namespace }}.{{ cluster_hostname }}"

- name: "[failover_role: {{ failover_role }}, cloud: {{ cloud }}] Wait 10 minutes for app to become ready"
  kubernetes.core.k8s_info:
    kubeconfig: "{{ managed_cluster_kubeconfig }}"
    kind: Deployment
    name: "{{ app_name }}"
    namespace: "{{ app_namespace }}"
    wait: true
    wait_timeout: 600
    wait_condition:
      type: Available
      status: True
      reason: MinimumReplicasAvailable
  

- name: "[failover_role: {{ failover_role }}, cloud: {{ cloud }}] Create or update DNS record for app"
  amazon.aws.route53:
    aws_access_key_id: "{{ common.dns.settings.credentials.access_key_id }}"
    aws_secret_access_key: "{{ common.dns.settings.credentials.secret_access_key }}"
    state: present
    zone: "{{ common.dns.settings.domain_name }}"
    record: "app.{{ common.dns.settings.domain_name  }}"
    type: CNAME
    value:
      - "{{ record_value }}"
