---
- name: Gather managed cluster kubeconfigs
  include_tasks: tasks/_get_managed_cluster_kubeconfig.yaml
  register: kubeconfigs
  loop:
    - aws
    - gcp
  loop_control:
    loop_var: cloud

- name: Bail out if a kubeconfig is missing
  fail:
    msg: "One of these Kubeconfigs is undefined -- aws: {{ managed_cluster_kubeconfig_aws is not defined }}, gcp: {{ managed_cluster_kubeconfig_gcp is not defined }}"
  when: managed_cluster_kubeconfig_aws is not defined or managed_cluster_kubeconfig_gcp is not defined

- name: Gather cluster hostnames
  include_tasks: tasks/_get_cluster_hostname.yaml
  loop:
    - cloud: aws
      kubeconfig: "{{ managed_cluster_kubeconfig_aws }}"
    - cloud: gcp
      kubeconfig: "{{ managed_cluster_kubeconfig_gcp }}"

- name: Bail out if a hostname is missing
  fail:
    msg: "One of these hostnames couldn't be resolved -- aws: {{ aws_cluster_hostname }}, gcp: {{ gcp_cluster_hostname }}"
  when: aws_cluster_hostname is not defined or gcp_cluster_hostname is not defined

- debug:
    msg: "Hostnames: aws: {{ aws_cluster_hostname }}, gcp: {{ gcp_cluster_hostname }}"

- name: Create Route53 record for the app and point it to the primary app
  amazon.aws.route53:
    aws_access_key_id: "{{ common.dns.settings.credentials.access_key_id }}"
    aws_secret_access_key: "{{ common.dns.settings.credentials.secret_access_key }}"
    state: present
    zone: "{{ common.dns.settings.domain_name }}"
    record: "app.{{ common.dns.settings.domain_name  }}"
    type: A
    alias: yes
    alias_hosted_zone_id: "{{ hosted_zone_id | split('/') | last }}"
    failover: PRIMARY
    identifier: "{{ record | b64encode }}"
    health_check: "{{ aws_health_check.health_check.id }}"
    value:
      - "example-todo-app-example-todo-app.{{ aws_cluster_hostname }}"
