---
- name: "[{{ env.name }}] PREFLIGHT: List nodes to confirm connectivity to cluster"
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Node
    kubeconfig: "{{ env.cluster.kubeconfig | from_yaml }}"
  register: result

- fail:
    msg: "Couldn't connect to ACM hub in cloud '{{ env.name }}'"
  when: result.resources is not defined or result.resources | length == 0

- include_tasks: tasks/_confirm_packagemanifest_exists.yaml
  loop:
    - name: flux-operator
      catalog: community-operators
    - name: portworx-certified
      catalog: certified-operators
    - name: cockroachdb-certified
      catalog: certified-operators
    - name: advanced-cluster-management
      catalog: redhat-operators
    - name: openshift-gitops-operator
      catalog: redhat-operators
