---
- block:
  - name: Wait for managed cluster kubeconfigs to become available
    include_tasks: tasks/_get_managed_cluster_kubeconfig.yaml
    register: kubeconfigs
    loop:
      - aws
      - gcp
    loop_control:
      loop_var: cloud
    vars:
      wait_timeout_secs: 600

  - name: Bail out if a kubeconfig is missing
    fail:
      msg: "One of these Kubeconfigs is undefined -- aws: {{ managed_cluster_kubeconfig_aws is not defined }}, gcp: {{ managed_cluster_kubeconfig_gcp is not defined }}"
    when: managed_cluster_kubeconfig_aws is not defined or managed_cluster_kubeconfig_gcp is not defined
  when: env.acm_config.role == "primary"
