---
- set_fact:
    managed_cluster_name: 'managed-cluster-{{ cloud }}'

# HACK: This seems to exit prematurely when you're creating a cluster from nothing.
# Do this twice until I figure out why.
- name: "Wait an hour for '{{ managed_cluster_name }}' to become ready in ACM hub '{{ acm_hub_env.name }}'"
  kubernetes.core.k8s_info:
    kubeconfig: "{{ acm_hub_env.cluster.kubeconfig }}"
    kind: ClusterDeployment
    name: "{{ managed_cluster_name }}"
    namespace: "{{ managed_cluster_name }}"
    wait: yes
    wait_condition:
      type: Ready
      reason: Running
      status: "True"
  register: result
  retries: "{{ wait_timeout_secs | default(3600) }}"
  delay: 1
  until: result.resources | length > 0


- set_fact:
    "managed_cluster_{{ cloud }}_ready": true
  when: result.resources | length > 0
