apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - managedcluster
  - secrets
  - submariner
  - gitops/cluster
  - gitops/placement
  - gitops/applicationsets/cluster_apps
  - gitops/applicationsets/operators
  - gitops/applicationsets/resources
