apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generators:
  - ./generators/pull_secret.yaml
  - ./generators/ssh_key.yaml
  - ./generators/cloud_credential.yaml
  - ./generators/installconfig.yaml
patches:
  - target:
      kind: Secret
      name: cluster-ssh-key
      namespace: replace-me
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: managed-cluster-gcp
  - target:
      kind: Secret
      name: ocp-pull-secret
      namespace: replace-me
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: managed-cluster-gcp
  - target:
      kind: Secret
      name: cloud-creds
      namespace: replace-me
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: managed-cluster-gcp
  - target:
      kind: Secret
      name: installconfig
      namespace: replace-me
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: managed-cluster-gcp
