apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generators:
  - ./credentials_generator.yaml
patches:
  - target:
      kind: Secret
      name: db-creds
      namespace: replace-me
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: cockroachdb

