apiVersion: v1
kind: Secret
metadata:
    name: cloud-credentials
    namespace: open-cluster-management-backup
    labels:
        cluster.open-cluster-management.io/type: aws
        cluster.open-cluster-management.io/credentials: ""
        cluster.open-cluster-management.io/backup: ""
data:
    cloud: ENC[AES256_GCM,data:cuDsYwt/Mi2c2xMz4YIGK58mGlfI3CmAMoqfmCnXbs+vXWlOHHUVZv2qT4UjUbTpGL+fRKm0TZHO88PjAx8gDjT3n+9V0v5ijX9JU4QPNusan+DGZO9vraoEBlTvKnordBn69fKfNE/NUOW7ZZW3HB6c2eRA2H73qS6umLTFKe7RRdXVf9bwOiFINJMm9wRkL2U7xgAKR6DwEKK2,iv:M1dR+g0HtGVAPjEVXBfn5FWCaiPHFzNCp3TZBVPf+D4=,tag:yZxcFX/SNVmmINW1ysuBWQ==,type:str]
sops:
    lastmodified: "2025-11-22T22:12:23Z"
    mac: ENC[AES256_GCM,data:otCyMIiURIXk56hWlIlepCptK6f9sDb2om9gl+CRKhQUfYuUzPZ/nAt7UjBgVy8fEPhXk/0Tdgcwq3brLqSGedKVfkZeFlgKhOaN7+GOCE2ZKZBtFf/mMXRF5yvX1BsYnt6vNgL3fPuY2igizH7QkBVwyD25SyjXw7dmaEC6Xng=,iv:8HFTh/XbcWz3bK9GHJBH6eoluhLRpThvhvRrxFLVFaQ=,tag:i8h+vtB9OveT+qkL95PF0A==,type:str]
    pgp:
        - created_at: "2025-11-22T22:12:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DeXeC3vKOE18SAQdAYmQQtKjA31qCXTkTsw+WLOZuliwD/cgE4RqBhOLUClcw
            rU/uatqV8H1XF7NmDE1g3a9Z2q6jdNWUWyN/MjYp1w1r2EoL2VVbwXBBXGg8C1w/
            0l4B4eIXdnkAfS4Gat0h+fngZbOEVRsDh+C9MCdJ+K2szVjT18PqXyQDiGON4WwO
            knO+Z4g1u6QcxmcjKoItlNTgU8ovWFnVnmFOFQk+vIB5/o8KpNabL1nJy/e3mXMB
            =7Qpb
            -----END PGP MESSAGE-----
          fp: 690EB362BCE71D5794727EF0382DB86937BB1D2F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
