apiVersion: v1
kind: Secret
metadata:
    name: cloud-credentials
    namespace: open-cluster-management-backup
    labels:
        cluster.open-cluster-management.io/type: aws
        cluster.open-cluster-management.io/credentials: ""
        cluster.open-cluster-management.io/backup: ""
data:
    cloud: ENC[AES256_GCM,data:8ixAzLrUsgyi6ks/ZuiR6iRtogh/m/4l8rIf1o7Z9pKt3BnFdHYaLN1nstgiYGeblSQp0af0y7Li1jlakO3jFBD2aK75ZowvCdP324aOMa7Ofatn+miZZXYMgolYNsYy+hkhgeBIXtG5mZECErVF1S/pViOdjHSqmQS/+Ds6Y0g5a4UUHvzYdl39z3c41hPJ5UXvDBab5eJyX3pU,iv:Mu3oBmaleWyWG7zUlS+VqNTbnZgC3DAn+Pw9PxeYIoM=,tag:FmS16+B5S9O9B9N3EVeXXQ==,type:str]
sops:
    lastmodified: "2026-02-18T20:17:45Z"
    mac: ENC[AES256_GCM,data:V4N7Ees1P2iK1ZMhpnkjvYXfvpRevHuIJARYB22Lmcjt+EePCJ/ibiM9dzwTPRRz792XhoQkK6BB2yuiiiKfg63DbbGGVP6CzVnPhTd72YJSTQsBYICxPzeiqyB0EktZlhLxrepMYQ9YeZJXDQ9KDitKnrZJOrn659yG7Vt8vjg=,iv:iQ3z4+75Z0XY3efCfBqlybV+csYd8346cK+HSPHwDNE=,tag:AXt/4kcP5wr2ShYgpU8eFw==,type:str]
    pgp:
        - created_at: "2026-02-18T20:17:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DeXeC3vKOE18SAQdANUx1Qbh0df/mBzN/aJ7ZudusSTozSCBlI+i4aXsjwhcw
            T68iDMIUhFdTF/ChH+dAoNxQbI690emU9z8ZNLpK6F1oB8kd0HpAY2Hg7PgfKJ9w
            0lwBsupi4Z2HuCr7l5ATnzUmBYZAgr2LMofOkdRPd9BK3gnIY+k/OTwowLhVdzO2
            v5R4vZHlLju3FTVkXOLAXXvnUoFABvVUMGn/zzH+sWZSBOCx0XKZohgf7RTpTA==
            =Bd2g
            -----END PGP MESSAGE-----
          fp: 690EB362BCE71D5794727EF0382DB86937BB1D2F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
