apiVersion: v1
kind: Secret
metadata:
    name: cloud-credentials
    namespace: open-cluster-management-backup
    labels:
        cluster.open-cluster-management.io/type: aws
        cluster.open-cluster-management.io/credentials: ""
        cluster.open-cluster-management.io/backup: ""
data:
    cloud: ENC[AES256_GCM,data:xHI8B1cMGmE8jc0KHSPEpw6sC5lPhEq9XN4Csdunxpvrb6ltJjPhcyXQ5zRAQ1nagvSjkK1eqbK/A9RyYgD4NoW9TEpZA0t/xqHzwYRkxYwd08xoz0TV/5X7R80IQrfFoSWS6URTa5fYchmbN0dxWxhqOdGJqyka97F7vOMKn1uZtwk/pJjppMl+5a+2ysn7+VkW0tGIQeM4tmaifmWjt19D6xQkfxV9+qaqwWTI6NpNU4DknISp590KjQzJ+Ebm1dN4RZYMb9I3Qnh7,iv:lwv2n5aQ+u8xWO1xZZSwUgACWkfCYtGJoRo7ED3bPl8=,tag:KxBsmoiF4PJM3cd776zl3A==,type:str]
sops:
    lastmodified: "2025-11-24T20:00:23Z"
    mac: ENC[AES256_GCM,data:wAHRSZOSlrraWRHrVLrjbzj7w+NpbgypLKkQCHfe608SOA0vcLIMBirxv3Vodw5yxn7bgkkQxnbCo725HZgG2sxtATNlDDloJNOTP/5iCR+A4v5yHzKBgzR1aXfxeP+MI+ouUhiw4gDofdFHbm/IhB/DMUpdvtM2+OKi35++Kng=,iv:LAx4ITuse/0TFOOUDyrtR6rlhMPJ5G5iR0AuK9mBwrQ=,tag:3HI7uBoWP0/y2OeEoIYITA==,type:str]
    pgp:
        - created_at: "2025-11-24T20:00:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DeXeC3vKOE18SAQdApM7DdZrUPtWKlspmb3pFj6A2odmOggS7CDdRKOybUQUw
            0FcSm1z3jS3u5dTMDRLdEdFGY2BPXifvTux/f0zwgD0OodAVA2LHEUYV2H+aA5QQ
            0l4BA+XBP5pgDUmwMlbCdQT4tSj8kVKk1n/d8OIT9Avdu7aOG2LZ45qEBqRSEwR1
            cSTm3vcpUx549V0Uanyh5tbLCxVrfl7+L2BQrQomFYQRAFfFPFI2XqWFy9EfCORs
            =Q+IX
            -----END PGP MESSAGE-----
          fp: 690EB362BCE71D5794727EF0382DB86937BB1D2F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
