apiVersion: v1
kind: Secret
metadata:
    name: db-credentials
    namespace: change-me
    cluster.open-cluster-management.io/backup: ""
data:
    username: ENC[AES256_GCM,data:kpW19ezDK/rOQNWdwXLFM0fBpIuZssftYwbXaFGiov4=,iv:YGaHVhYCBgZIDOXT6m0WzLeeyckneRZ2Fgpos1UFBWE=,tag:MB6V11aajS+bqAfRizvwgw==,type:str]
    password: ENC[AES256_GCM,data:kYB2ByG7jr29w6/YO69dH2vrIV2mK5P10TMQh0lIc4KGuGHWMXfJ3gWOtnGUCR7+t+yD/mtKWrZ8gxAY7spHkFIV7cToLtfWht7rbUVihur2HKCxgMwEtA==,iv:c77P6lvD6JpjkRawofQjWeQUobGB0HnrX6Z1FbqgE3M=,tag:vrkVuj2Ss+2+Pkr9AjiYuA==,type:str]
    database: ENC[AES256_GCM,data:mUehYSIJliEmYHMBxQNxrUbdD8Bd10t0neB4RLD0WkE=,iv:6Cpt+yD0lzCrj/oHWIUuqOMK0PhhOQeeHU3uz4dA7+I=,tag:QyuiaFc/I8SnRUTlO6dM+A==,type:str]
sops:
    lastmodified: "2025-11-24T20:00:25Z"
    mac: ENC[AES256_GCM,data:XXPr/dlBMjLtdBFHkpqOZ3+9hqqksNk3qTucTLz0Gl7Q8lg2Fcnag116MT49UU5WTyPNzqjAK3KC1VgtnRjpPTp24Nw709qtZ2yCFZfmZKreEbP7lephjQLgDJg5/Uk49me4ArXM7yHNFHtIg6AdcQfB0eZHbR+GVbNgPWdCeJo=,iv:wTL1LED40RI7rQJU1LOkd3Pl/KS45rgmGeDt9fWK+60=,tag:MMUuWqITK/W83Sp/WIbI3w==,type:str]
    pgp:
        - created_at: "2025-11-24T20:00:25Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DeXeC3vKOE18SAQdAMLAC0s0JgLp2Hv+QK2Hn5xFpUXFWfDSYCc8mS6eggkow
            bH639otS5VBFoeY+ZNYKfTwAuuB6DvbDPafUefOJgrvDpvRbQdPvJf0cyuXsWPo3
            0lwBRHpEqm8Bh4S5bRUtIqpA3iQrAkzDvd16eNsCjGifnnm8ROJvG2tVgatp6v/I
            TgE7N5NoelQdDEUW41iEkiJmGgdPd77fCgQhi1WsrRv8Q4v5IUAmaNS61dg+mg==
            =Q4Tq
            -----END PGP MESSAGE-----
          fp: 690EB362BCE71D5794727EF0382DB86937BB1D2F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
