apiVersion: v1
kind: Secret
metadata:
    name: db-credentials
    namespace: change-me
    cluster.open-cluster-management.io/backup: ""
data:
    username: ENC[AES256_GCM,data:rTUmDuf+My6736FjjHyjiruPgioke8pHuTaSP6/aZgk=,iv:uh/kgB+ZtJOc/CVRT7idLperCox1TD/eSsw/LTIh1dw=,tag:lGwd+2KVwsPovvzU5w+AQA==,type:str]
    password: ENC[AES256_GCM,data:FdTko6MMRcvFtJfEPk7oMK9Uvh11Y4WmakOP5fT0FZAsodd09FozI3gEw3Mh2ImorbCVQfENe1PYMfKrBI+pGqtKIE9e0VcNbdTjV7W7IfbM7bh8Bjxtfg==,iv:nUAba5TRvJYxDrs0jG3hTs+W9ruIARz/f+g60t4Ne2o=,tag:1JcCbr4GQzVHaFGpA4wWpQ==,type:str]
    database: ENC[AES256_GCM,data:QGX8vXuU/oXvV3WzlmSmF7toyRaEFKT1oQl0qTcny44=,iv:Q7o5L3xZhQtJMk7yXoB2tAKg6/hCOuetgfqZQ1bwKP8=,tag:/6jOjVp47zyw1eXrfbvxcQ==,type:str]
sops:
    lastmodified: "2025-11-22T22:12:25Z"
    mac: ENC[AES256_GCM,data:ItB0axAFKVPqzt2RZEBemMduksyvtlPsNo21cbPmTxYRBKrCsJw/SrgId+B8GAqMHUAkizmSw4/6+NWgEX+3GAegeshdl5jR6MxDaMA8To4mOa7Srw1+mLIgRhYL+ckDfjhiOppa0+WiKLMYQu4w2pVI1ZyM209x7mJH8EdcVKg=,iv:GkVeVWEZ9ltXvAyzZ6P9+NqF67gqbBwq6qhUNzCCYEU=,tag:pO7EQcGgrpXvSenJxDcCqg==,type:str]
    pgp:
        - created_at: "2025-11-22T22:12:25Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DeXeC3vKOE18SAQdAmIxElUjpABFlUaP05UGlVeTfIi2DjNmgWpyEr1owvwAw
            68cTrKFRR7p9mHOQeZL3oMIq+kfJvoEs+1kINIQDkK5ffKWtHXQADoqQ3HhTkMXe
            0lwBvRchRwolrSJSYO5fmjaLLr+U4kaRJblZQI/NBDrq3bH2dulUhB/B92iMc62r
            uQxIB36NPHFjP+UAGpacrq8+MJoTDiN59KaV7kzw7Pj1p+V6WuJOiOhsOki6EQ==
            =DVGB
            -----END PGP MESSAGE-----
          fp: 690EB362BCE71D5794727EF0382DB86937BB1D2F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
