apiVersion: v1
kind: Secret
metadata:
    name: db-credentials
    namespace: change-me
data:
    username: ENC[AES256_GCM,data:hQVnAI8OOQQ5hhS1+zu6/R5L9f/Sx8Bvp4fnuS4asbw=,iv:Di5OvDQO/WzF1zX9+1GrSVnGF5ENQa61uDZiiNONRdE=,tag:qJ7odU7jrZXxhEEAdVuw2w==,type:str]
    password: ENC[AES256_GCM,data:PT3qDnX4P4E5KXW6RnWHGub2YMiFs8nFQdK8EW3XE6ts6IVXnSv7xgD5GwUm1hziV0oTK7SGggUIbf3d+xH/qsVLCAqMHvmauu850+aQjKlE2i4CTs9d/w==,iv:hM8MFaExzEAZ7ufiQN/yPKo/zAv/dsDDGGxOL9nffh8=,tag:7McrNI49JCWpj5TLtic5iQ==,type:str]
    database: ENC[AES256_GCM,data:UQE6CXr2qxRA+09R+o9+/R5O3FlqFIKLGMq0OR/Zo30=,iv:a8hnxr1BXKpgTkCJKOtjwR30PeevxiJ8NaX1cc1/p48=,tag:bfVWFjcABUHQjDMAFpT+WA==,type:str]
sops:
    lastmodified: "2025-11-17T01:01:15Z"
    mac: ENC[AES256_GCM,data:SAc92k87LJZXV8sBA3f+mnvdzptPTzZ2R3J+vkTDLlBAoHc8nt4otcJxZN6QBLF1vQcG20LebzQMP3WZkohFZw4fh7wkMfvhn4EOz7csBIh7AoXVHeGUrnY6boYnGV6jIWq+LVhwGOwa/WHP19kjRnyRr+yqnzukhz2KAOnvaHA=,iv:LmhNybbD/+9yoFx0eaA9TCPM0bhNi3kRIUyndbuCxJs=,tag:2B9c9PcJTf9ESiaJtJD+3A==,type:str]
    pgp:
        - created_at: "2025-11-17T01:01:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DeXeC3vKOE18SAQdAfJUl97wfIY1WHKtIe2KS/Qt3YXLX3Eky55NU1X8vkWUw
            PTKFXFcW0i7aGYjiLPzN3b1ElbhUTosbxLy2D/o5QsJKplBS9mvbl3rjsXnfW5IG
            0lwBurwEhYhAftMjnWQjkTHJOyr5h3SAGOf3VSAJ2IgKmzOdEsvv8FWbyJLukouX
            sv4juL7B2Qd1LqUDYqxPtCnO9n2GXHbVDyuOuImMIERqi4SxFgp9KJwIVQDWyA==
            =cdZb
            -----END PGP MESSAGE-----
          fp: 690EB362BCE71D5794727EF0382DB86937BB1D2F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
