apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../../infra/components/resources/acm/multiclusterhub
  - ../../../../../../infra/components/resources/acm/multiclusterengine
  - ../../../../../../infra/components/resources/acm/managedclusterset
  - ../../../../../../infra/components/resources/acm/backup_schedule
  - ../../../../../../infra/components/resources/acm/managedclustersetbinding
  - ../../../../../../infra/components/resources/submariner/broker
patches:
    - target:
        kind: MultiClusterHub
        name: multiclusterhub
        namespace: openshift-cluster-management
      patch: |-
        - op: replace
          path: /spec/overrides/components
          value:
            - configOverrides: {}
              enabled: true
              name: cluster-backup
    - target:
        kind: MultiClusterEngine
        name: multiclusterengine
      patch: |-
        - op: replace
          path: /spec/overrides/components
          value:
            - configOverrides: {}
              enabled: true
              name: managedserviceaccount
    - target:
        kind: ManagedClusterSetBinding
        name: replace-me
      patch: |-
        - op: replace
          path: /metadata/name
          value: global
        - op: replace
          path: /spec/clusterSet
          value: global
