apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: example-todo-app
  namespace: example-todo-app
  labels:
    app: example-todo-app
spec:
  source:
    type: Git
    git:
      uri: https://github.com/carlosonunez-redhat/go-todo-app
      ref: main
  strategy:
    dockerStrategy:
      dockerfilePath: Containerfile
  output:
    to:
      kind: ImageStreamTag
      name: example-todo-app:latest
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}
    - github:
        secret: supersecret
    - generic:
        secret: supersecret
