apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-todo-app
  namespace: example-todo-app
  annotations:
    image.openshift.io/triggers: |-
      [
        {
          "from": {
            "kind: "ImageStreamTag",
            "name": "example-todo-app:latest"
          },
          "fieldPath": "spec.template.spec.containers[0].image"
        }
      ]
  labels:
    app: example-todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-todo-app
  template:
    metadata:
      labels:
        app: example-todo-app
    spec:
      initContainers:
        - name: wait-for-db-up
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: database
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: port
            - name: DB_URL
              value: "postgres://$(DB_USERNAME):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)"
          image: curlimages/curl
          command:
            - sh
            - -c
            - |-
              apt -y update
              apt -y install curl
              echo "url: $DB_URL"
              getent hosts "$DB_HOST"
              curl google.com
              curl telnet://${DB_HOST}:${DB_PORT}
      containers:
        - name: example-todo-app
          image: image-registry.openshift-image-registry.svc:5000/example-todo-app/example-todo-app
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: database
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: port
            - name: DB_URL
              value: "postgres://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
