apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-todo-app
  namespace: example-todo-app
  annotations:
    image.openshift.io/triggers: |-
      [
        {
          "from": {
            "kind: "ImageStreamTag",
            "name": "example-todo-app:latest"
          },
          "fieldPath": "spec.template.spec.containers[0].image"
        }
      ]
  labels:
    app: example-todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-todo-app
  template:
    metadata:
      labels:
        app: example-todo-app
    spec:
      initContainers:
        - name: wait-for-db-up
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: url
          image: docker.io/postgres
          command:
            - pg_isready
            - --timeout
            - 60s
            - -d
            - "$DB_URL"
      containers:
        - name: example-todo-app
          image: image-registry.openshift-image-registry.svc:5000/example-todo-app/example-todo-app
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: url
          ports:
            - name: http
              protocol: TCP
              containerPort: 8080
