apiVersion: v1
kind: Service
metadata:
  name: example-todo-app
  namespace: example-todo-app
  labels:
    app: example-todo-app
spec:
  selector:
    app: example-todo-app
  type: ClusterIP
  ports:
    - port: http
      targetPort: 3000
      protocol: TCP
