apiVersion: v1
kind: Secret
metadata:
    name: portworx-saas-key
    namespace: portworx
data:
    saas_key: ENC[AES256_GCM,data:cxrSpybg6ttfQI/UpBNSkMJIk7eBW1gg5YvGt6rSSJszIpLZs5FElVtDwgFGeaarTPZQy68KyLq5KpuZB1yFDvfbmYm7CQyRSXGR86jLGIBBvszai5mp40cOH2FDIXMZO+5k0auqTKezErfa3I+CwkE/ZQMXS9coqJje1m9hyC2ofVMbt5JR6INUGLbUvHR77xJQD5wYDirWu8hKcs4gQoA1VRN5nrhUu5O7SmY5+a7VyVXZgFsc9Z+rBH2Lu/gNJhf9RWtg0uA+cdzwQa2+KyZTaiZoNNYaea0y9cpPymI9pBWE7kntkTWmo8ywEnf5YA44JqEnnQQjb3HdDRP/v/c0moHsjkMm4SAWi5fM4bxnqClk4YnWEVs0PKMgn4zyRpAAXqlp3bGWL3sgwxzSzsA9NITR27KzTkl8Nk4rn/45jOXz+C+ai+mkfm0/XoXa8/nZFE3P6mdMhsX+LbF0rXtM6u8hA+DIAWm0r1pSlbnli+HPcUUYc6G6ffCGRsuStqxRxnN8/7cY4jyCShHJtLM2kEinn6qtbCu99Z/N6GG/SvJh6BdAKgLWNJz5ISRsWzcRejXRymtaFgQnC3qieADh6ugYLGBgSBZF4bn8tvoS74kxdO0upvL3k4HwrwIXpxWhxOPzkSI4caxPWlNweVHAdZFVSJlo1bvJrFt5ZTDb2PEER4XX9XwASlpUM37EdvBwX0tlO0+1FrDyp+Hm1XKgRfyuXy54j4iPClWjFngp2sFEge54H2rK2uM=,iv:GIMyHvg/TV+V7VYS7jIvJHfIBo+WD/LUTRvMMsik9WA=,tag:OiLyH2xNM7CsUoF1QDOdBA==,type:str]
sops:
    lastmodified: "2026-03-05T23:34:45Z"
    mac: ENC[AES256_GCM,data:gs0sc+L83D1TckagEE12Fm9b6Q/UOC8ct/uZ/3XoMvsVDjkfOGRYAtf5A82mHak+ajLl8newswk6/YDLyRelKThgI2mrs/zdWWQ9zQFVSaDuCBHwlbjBR7ZY9K3Z3eo21ILe6Fw9aTNyZunoj3smuz26SI55ywLM/0Ih/RuHlZs=,iv:rXJWESI6G0AeTFipyUbhpVSodrusEmdc0AIcOJxyOac=,tag:LShMLdb7DHi3QFnKM4unDg==,type:str]
    pgp:
        - created_at: "2026-03-05T23:34:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DeXeC3vKOE18SAQdAN25ubHabKFsPAbw3uguQrpphMEj8iZiScsDQWyWOcXow
            XQqv/TqGrUr5WVFwbrOX7HcHl8RrIrDk5Z4igU+L+5qAZWp73DtE/7pF+FZZyLIx
            0l4BKNfYAfHRWV0uhegXH3fPqSxM9aCCkUFzYdd4evcBTNiw+rvf49VuwvK/yxjH
            K/oTR2gJhZkocCNHWtf1zXZadZpU+f8mCGGJ/GwtRkSCN71095rTKWSWCLIixfu6
            =86s5
            -----END PGP MESSAGE-----
          fp: 690EB362BCE71D5794727EF0382DB86937BB1D2F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
