apiVersion: v1
kind: Secret
metadata:
    name: portworx-saas-key
    namespace: portworx
data:
    saas_key: ENC[AES256_GCM,data:JjKF+wP/olNiqpotXd6ELwMQzyRD8CDeqnGUWMGyj8fI423sw4LuHPifsPgutk8osuPSZa6EUTRt+X7Q+Oa7mSe4BeWsY9vFu62ooSQHoREwBWC2Qg0fBYApTcz47yjZIXAB21GNju2bLZe3qidxioACvB0PBvXL6zu7xDL6nznPtpwEBGA0rjbHgB88Wz4KkGqmqBxN+lgxGcggz5l2P+emxs0Bs9mPBF3Dw7hlAQtbzzNYffEpSKQOIL0KzupdLl5U10vtF/90hgn+1mDUpTOQhpvHwHl+I8lezkf5K0zSuZLcfPgIZS0iAx5q6LT1IC4sGcFWPeMIt8c3v7uqN3MEOwUei8OIfHx0ZiE+/VomZmDeyKGFs8x7r5AgTN+/h3s2tMge7SE14NSnOUWxWIu/yydC7+9CKmLVSFrTzmZ4NSVU726giXwFLBlXShU5iZYtQO6EbW6oSUVKdflHKb7X9CLIXPsQftYrow8APR39eoSq2fSQOfSjcRQ6bQusYIZsT7hxaXrX5SywSGPcCTNCqxab3FMnmXAdDZyJvlSBP1ORlED4tMjbF0uGnZyWz1bY8vd+vyta0EPdqK3RaIDj//J9rOpi+IpXNZmUTklZLtit/XwqTR0UCBsEhYpD/7TzXge2H4fKhyoIPA8NjQoLxATZf+TAku636J+lLWri151+ouhMldqGyifuSb3BRkK0vPZ1X9hwz9yrr1/0fCVmnWttTxFh5VfO24WnpgriXbaRKOxNEeh7fjI=,iv:O1QnFtwj57xNQzluWJABs1i2ohO7VPwSn1lyAuWX1VQ=,tag:c1186gJx2AR7znkkeGEHlA==,type:str]
sops:
    lastmodified: "2026-01-14T19:06:37Z"
    mac: ENC[AES256_GCM,data:q1MXPLMee+3xcOJ5MI337N94mN6jRBqJurnx8ZGe68OPEiIMYdGs/U6PjubupCmTfkJ/ZILJr5/oXqgBl7EWFRnCWSb/Npg8sC/4jFvAZMRTOP2DtSjgW2eP9ikwgyrsPPxDuZIDcbcmLYzK+ZZhz0PBcoyrcC1vwD+hdPU6uTM=,iv:jI/LmPr3QVDYvhGpAlgQunN+SrMIW3+K5r8LEl722H0=,tag:cyIUAEREwCYs4lP7cDZ2MA==,type:str]
    pgp:
        - created_at: "2026-01-14T19:06:37Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DeXeC3vKOE18SAQdARjz5h+fEP1YOuIl8CQeZYvmoTY+sMsBJRbpdNTSqP0Iw
            p+lDqgmArv7h3iJtsacIePSCzZqyZ3fJBzYMzhuP6dXNRJrzcy6euyUmLYztNfg/
            0l4B0NrWjg7WzoLvm2K5hIJUJ9LRtctDnPgvKnz2VJhcqmXipjEgMyUwNtcgZZIB
            Z9r5EMyhpmLqit1NNlkFan1FU02y6fe+Oh9eZECarr9ZSCeZ/OjGx3oWrCRyXY4K
            =5if0
            -----END PGP MESSAGE-----
          fp: 690EB362BCE71D5794727EF0382DB86937BB1D2F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
