apiVersion: v1
kind: Secret
metadata:
    name: portworx-saas-key
    namespace: portworx
data:
    saas_key: ENC[AES256_GCM,data:kxmC3O0rrETzuKYFq8pbltmPzzuBA66R+nNIoQpAIqQvyITUZ8WHYQGYLjOvZlcWjCKAj+CmnyKmavH5/QgyZ+RvSBvo8oLQb9sT2f23ZmW0+pgmyKO383NaooflAkRpL0/0VYlbH9zAwIKvwek8JDeLBykqfV94eiq1uoZ2PgSk184sjivLu+Kg5dq2CGqhVrHMb239+HBcDz2n23VXLPrl5PM5WR1+D//dtsorIBD/mOui4HcOAnfy+EtvsDtqiN5B5HwkGnZd9QtILWqZnjIBgm7rws5I2svX9vaVufTWRQH/AdJsgOnzdL+qjqZLJGx3p8WXUWCJO2aWOKh7abp+xQXcLl1CPtLfKUR0cSJK2Odb+lPqFbonw25h76OQomawww0j3rRM1r89B6HD6YQVpymYX62gL3/dwYCKu96wqaqodzIju+uqaBiP9V2S6cTIfWss8Bc+n/9fM3s8N4d6KGphsF8CPUN1I4R1GDusMy3F8UsnRD9B4B9swaM1qO9NGJJ027WuoyHUHmk4ufewOTFdYysdYmk/6dtYeyAUiTD4iGh5PAFHZzAydVrLzQy8UpVhFrJDTz/pdO1BiR0CsK+Ci/nFdRsWJYSm8WvM5SxP9pJDqDqwpDMAVsgrdfernEPaGA2wgn4VdQqoGHV3oY8SNBNv1CgND7zVSxA0bgz9L1qU9W4I582FAWPdjs/79bpfwumanTei/Ia7zwytFtijpwtfdq0YoauKnaIDXMXYn0G7hLJoE80=,iv:nP5p5s6DI9eQjRKrRpAqqG5jsReiEymj0uBLjtBSKXA=,tag:FIQIR2kWmw4+x1UQrcklvg==,type:str]
sops:
    lastmodified: "2026-03-05T22:56:31Z"
    mac: ENC[AES256_GCM,data:4MCGRqYILKO2VlYJoQDh1A/0RF8+gwG0MrgbE6k5F/aK/LlWa6LtJA0vz30g2Qgnfhx5pfdtZEiRbWZNmxWi/qxiepqrFFwV6TXGvxxX9HX2gVYwgNJx9sxOEx9doyBE3xgwr2C9JKo8nnipKLHKt2oS+eM/kZdT6eCrCSInRKE=,iv:Nfnzj6XxlNVO7mpn6dOyzZ+i5gDHi88Xatqu2D5wAuE=,tag:1RUuqnCN7g0gdBQQs/1BmQ==,type:str]
    pgp:
        - created_at: "2026-03-05T22:56:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DeXeC3vKOE18SAQdADGtWmM/FNdViXk2SP5oklFwjFTPJvHfNZQy5uekxqF0w
            w+3kwUp/HbIL3OSFpbu/prra9eVgnVKEL/q+t5FsbSI9/zMNUVScWXMCUOwVuatG
            0l4BqhBj20vIcWBF4dteusZs6607pj5+kQJVEf7FrGPr1ja/xRXfk90kFUBSHDZY
            vLeAQl8MmJXEi3Y9e2p5hro6fIFHs6OeO5OJctkQFAex6gFftr1JUaLgVW7zanTf
            =N/q/
            -----END PGP MESSAGE-----
          fp: 690EB362BCE71D5794727EF0382DB86937BB1D2F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
