apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: cockroachdb
  namespace: cockroachdb
  labels:
    app.kubernetes.io/name: cockroachdb
spec:
  port:
    targetPort: https
  to:
    kind: Service
    name: cockroachdb
    weight: 100
  tls:
    termination: reencrypt

