apiVersion: v1
kind: Service
metadata:
  name: cockroachdb
  namespace: cockroachdb
  labels:
    app.kubernetes.io/name: cockroachdb
spec:
  selector:
    app.kubernetes.io/name: cockroachdb
  type: ClusterIP
  ports:
    - name: https
      port: 443
      targetPort: 8080
      protocol: TCP
