FROM registry.access.redhat.com/ubi9 AS oc
RUN \
  set -eo pipefail; \
  arch='x86_64'; \
  case $(uname -p) in \
  arm*) \
    arch='arm64'; \
    ;; \
  aarch*) \
    arch='aarch64'; \
    ;; \
  *) \
    >&2 echo "WARNING: unknown arch"; \
    ;; \
  esac; \
  curl -Lo /tmp/oc.tar.gz https://mirror.openshift.com/pub/openshift-v4/$arch/clients/ocp/latest/openshift-client-linux.tar.gz;
RUN mkdir /tmp/oc && tar -xvf /tmp/oc.tar.gz -C /tmp/oc

FROM docker.io/library/fedora:40
COPY --from=oc /tmp/oc/oc /usr/bin/oc
COPY --from=oc /tmp/oc/kubectl /usr/bin/kubectl
COPY include/pip/requirements.txt /requirements.txt
RUN dnf -y install python3-pip jq yq ansible python3-jmespath
RUN pip install -r /requirements.txt
RUN rm requirements.txt
