apiVersion: v1
kind: Secret
metadata:
    name: cloud-creds
    namespace: replace-me
    labels:
        cluster.open-cluster-management.io/type: aws
        cluster.open-cluster-management.io/credentials: ""
        cluster.open-cluster-management.io/backup: ""
data:
    aws_access_key_id: ENC[AES256_GCM,data:mmP4mB2wob+kos8t9PdlfJbYyTf+oNR2ZFQG2A==,iv:KLYJqHil/JK0tZi8B2DcI1dMKkXYIe7OuqVamADwL7Y=,tag:I5+STqBrkwjgL821pIH2uA==,type:str]
    aws_secret_access_key: ENC[AES256_GCM,data:ZaZhw4B9sw0+pGkzuBVxgtPwUMxcvvGKVPybIgxSBxvFtHSe+n0AOuIzvb2sPmbdQOTa7w/+unI=,iv:mGdApBxgxsieW/zw36gEki2EzKvINQ6/BeUQG8iQChw=,tag:AXvXg5GXyyVV8btQTAW1nA==,type:str]
sops:
    lastmodified: "2026-03-31T21:41:27Z"
    mac: ENC[AES256_GCM,data:OUzRxB/TGFTvabYVsYLS0S5eRgFCzDfK8jb4m4rAYS6CjkcjD50swSFtvgk73UkaKASiPE+mc8zBtA2u1v8pBk/eR7VIYncmDQoC8hXxtpWOphyQa2BFRWIiYTh7ysVXHahIfTswl8+bcClOBk6v2sBqtmHKbIdJTElvaYv5FFo=,iv:pLljE5n/pUVg6RxCiKmgKrqQ7Bt3ofEKI0kjCZ5DrkU=,tag:081Cdnr6pRPkFDz62emFFA==,type:str]
    pgp:
        - created_at: "2026-03-31T21:41:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DtVMEJohTtwUSAQdAa8AsCYxYxwgRM2F52h/8dnq866dgrtisXTKx7iwxqVcw
            LwMPbzal2w6IhdyAUAWjmIipMThqI7HFGCbM54/+WeY4f1hMCnYbMh8eL9gejf3w
            0l4BDTHKA2fLvJtqVtoV0mcrujXhsR1HEapvCBCQp+b87TRZyXXlJcjM3KoCgJCh
            u2XJxXQD+yoMEdl/ceouRewdj52gcHdvuluRKj8Omz/7s77D/gH2/2tGa3AM8ZmE
            =44tW
            -----END PGP MESSAGE-----
          fp: 6FD445DC1FB700FBE7A7ECC544CD8DE2673D3065
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
