apiVersion: v1
kind: Secret
metadata:
    name: cloud-creds
    namespace: replace-me
    labels:
        cluster.open-cluster-management.io/type: aws
        cluster.open-cluster-management.io/credentials: ""
        cluster.open-cluster-management.io/backup: ""
data:
    aws_access_key_id: ENC[AES256_GCM,data:s/RlDkDxuSQ0BbvtAeKeDMl9aEC34oWPkpl1Hw==,iv:mSXwYHnsYSnBl3Db0Vr0sHodSegRF0qO4cpYHsGBYyE=,tag:ygFIGvo8RmDHKOulX11Nmw==,type:str]
    aws_secret_access_key: ENC[AES256_GCM,data:47AtnzUSP0VACm3f8UAlztYimETRQPnlpMQmnjHsjO2jlBJ8KR7wZpCgZFxFmlCdzpDwDZWOCc0=,iv:aYowyvK0PNWFZqu71woXHn8Q5WxI8/bfqXJVPSk+V3s=,tag:FT3SZz/DRb5ElPjZyIuS9g==,type:str]
sops:
    lastmodified: "2026-01-14T19:06:35Z"
    mac: ENC[AES256_GCM,data:oTgJkmCArOi/U9jL3nLL3INV8GYgXucKWg+0AR2G3R9cwQVOwJ9U9+KASTJpgOPqG5oXaGgiGxWCr/7RwG5VsUGy1q1MSnj5xVJ9xqaKOHyAROZA+PPzy+4D76V5BL9z0VLYK4nPqV1isa5MdeuD9LZQpKjyneTnZeihqC2ZWYY=,iv:q8BQHoSkJuIFeoq4PK5fGpjZdJAAQPhRlqxnGwnZE8Y=,tag:v73CAgvy+cjxrdOe0QRw2Q==,type:str]
    pgp:
        - created_at: "2026-01-14T19:06:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DeXeC3vKOE18SAQdAxnRRsgmFGmvWA8LH0pLs1CBfdxbfrMFzOGsC4xo7hC8w
            hMSXGq0Q7z8toE74qsk1kAmPOP6oDhlXpkvXYnqNV+7DfnEY+k9KFU1Y6AbzS/cy
            0l4BT8xgRag7PQByitvEgE6wJ9RKF/2V5AujozcygoMfSvoQsKVDstdeuhXR0FWH
            C30anyebs1kB0QZ1CjAP2KiE2TQhJg8EC5razDGhhEbVbs7X04KrapJ2cfd/2Y9T
            =PWH8
            -----END PGP MESSAGE-----
          fp: 690EB362BCE71D5794727EF0382DB86937BB1D2F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
