apiVersion: v1
kind: Secret
metadata:
    name: cloud-creds
    namespace: replace-me
    labels:
        cluster.open-cluster-management.io/type: aws
        cluster.open-cluster-management.io/credentials: ""
        cluster.open-cluster-management.io/backup: ""
data:
    aws_access_key_id: ENC[AES256_GCM,data:VroO/uquDVKhi1P1U0H4IOMv5QMKAET5DjK1AA==,iv:Livv4967HmuGM3cPxqsmOVDgGwRnRvWA715kvCa729c=,tag:cuz1vKfVmIeVDf0J3/bOpw==,type:str]
    aws_secret_access_key: ENC[AES256_GCM,data:6JliCuf+43d2yf4mdahW2LWN2u0c8NQ2gkBGpq6f5dQaZH+IjwkGnRUyOI0pTNF67kn0Qvn8gSDWymti0SbxYTwMp0ukVUF2FA45f2Aj3/Ujaa0+J8cl+inxU6mCDaVRLfw5oA3HTAI=,iv:PclNDBQvEhWmkJ/GbPN3QwGyeBEDTSBIaFcaZG/h7kI=,tag:OQH3EmzPeWAXKK0Gtm1FcQ==,type:str]
sops:
    lastmodified: "2025-11-24T20:00:23Z"
    mac: ENC[AES256_GCM,data:SUvtxzBcOSbwnMLXlNOEjCzXywqgTtB+BaMiGuuGTFK8qgquSLcIlul3wwrpwV0qXX8B0/yIZzRViFcvjT/9ayVY4juBpb2RIJDApsgjSmZhL9ZKWr5ODu2APd2P/+rqSw6Lp6df4dG9NOaaQbaYinG57EmRAehwFBMIVGxG50w=,iv:Ce9iVA/hBzczVuhSPXYi6iyd/nFoUYY4HY1nCzuVPYs=,tag:yJQGCiUHfw2XwjKQaLMbWg==,type:str]
    pgp:
        - created_at: "2025-11-24T20:00:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DeXeC3vKOE18SAQdAt2xRqeqFnF7m9duvP9CRvX+3+gNfPd77MoJvOfXqmG0w
            5qfRsrXq8R8L9YvZYehIWJ7ZNfMHZeEEHnAOceo9K97wheqnh+O9x8FBOxghGmu9
            0l4BYzRooZObsFCu7/lvJ8alTF5OEAtxHhyb9AWrOKC+5KjTY+sfBAuiYQ0HRuH/
            yXveHFlRHyYDCWk34gCGI1zJ1XTHKLIicEpbcSCvJybaaYwyK/D4pnN1MBxlA56v
            =rlAc
            -----END PGP MESSAGE-----
          fp: 690EB362BCE71D5794727EF0382DB86937BB1D2F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
