apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../apps/todo-app
  - ../../../../components/resources/cockroachdb/cluster/secure
  - ../../../../components/resources/cockroachdb/admin_tasks/create_database
  - ../../../../components/resources/cockroachdb/admin_tasks/create_db_user
  - ../../../../components/resources/cockroachdb/admin_tasks/create_db_table
generators:
  - ./credentials_generator.yaml
patches:
  - target:
      kind: Route
      name: cockroachdb
      namespace: cockroachdb
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: example-todo-app
  - target:
      kind: CrdbCluster
      name: crdb-cluster
      namespace: cockroachdb
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: example-todo-app
      - op: replace
        path: /spec/regions
        value:
          - code: us-east-2
            nodes: 3
            cloudProvider: aws
            namespace: cockroachdb
      - op: replace
        path: /spec/topology/zones
        value:
        - locality: region=us-east-2,zone=us-east-2a
          suffix: -a
          labels:
            failure-domain.beta.kubernetes.io/zone: us-east-2a
        - locality: region=us-east-2,zone=us-east-2b
          suffix: -b
          labels:
            failure-domain.beta.kubernetes.io/zone: us-east-2b
        - locality: region=us-east-2,zone=us-east-2c
          suffix: -c
          labels:
            failure-domain.beta.kubernetes.io/zone: us-east-2c
  - target:
      kind: ConfigMap
      name: db-config
      namespace: change-me
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: example-todo-app
      - op: replace
        path: /data/host
        value: crdb-cluster-public.example-todo-app.svc.cluster.local
  - target:
      kind: Secret
      name: db-credentials
      namespace: change-me
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: example-todo-app
  - target:
      kind: Job
      name: crdb-create-database
      namespace: change-me
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: example-todo-app
  - target:
      kind: Job
      name: crdb-create-user
      namespace: change-me
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: example-todo-app
  # this isn't how this would normally be done, but
  # it was the best solution at the time.
  - target:
      kind: Job
      name: crdb-create-table
      namespace: change-me
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: example-todo-app
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: DB_TABLE_NAME
            value: todos
          - name: DB_TABLE_COLUMNS
            value: "id UUID NOT NULL DEFAULT gen_random_uuid(), text TEXT, checked BOOLEAN"
