apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Restore
metadata:
  name: acm-restore
  namespace: open-cluster-management-backup
spec:
  restoreSyncInterval: 1m
  cleanupBeforeRestore: CleanupRestored
  veleroManagedClustersBackupName: latest
