apiVersion: batch/v1
kind: Job
metadata:
  name: crdb-create-user
  namespace: change-me
spec:
  template:
    spec:
      restartPolicy: OnFailure
      volumes:
        - name: certs
          projected:
            sources:
            - secret:
                items:
                - key: ca.crt
                  path: ca.crt
                - key: tls.crt
                  path: node.crt
                - key: tls.key
                  path: node.key
                name: crdb-cluster-node
            - secret:
                items:
                - key: tls.crt
                  path: client.root.crt
                - key: tls.key
                  path: client.root.key
                name: crdb-cluster-root
      containers:
        - image: cockroachdb/cockroach:v25.3.4
          name: do-it
          volumeMounts:
            - name: certs
              mountPath: /certs
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: database
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: port
          command:
            - sh
            - -c
            - |-
              host=$(echo "$DB_HOST" | tr -d '\n')
              port=$(echo "$DB_PORT" | tr -d '\n')
              user=$(echo "$DB_USERNAME" | tr -d '\n')
              password=$(echo "$DB_PASSWORD" | tr -d '\n')
              ./cockroach sql --insecure \
                --host "$host" \
                --port "$port" \
                --certs-dir /certs \
                -e "SHOW USERS;" | grep -q "$user"  && exit 0;
                ./cockroach sql --insecure \
                  --host "$host" \
                  --port "$port" \
                  --certs-dir /certs \
                  -e "CREATE USER $user WITH PASSWORD '$password';"
