apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets/portworx
  - ../../../../components/resources/portworx/storagecluster/gcp
patches:
  - target:
      kind: StorageCluster
      name: replace-me
      namespace: portworx
    patch: |-
      - op: replace
        path: /metadata/name
        value: gcp-sc
