apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../components/resources/portworx/migrationschedule
patches:
   - target:
       kind: MigrationSchedule
       name: change-me
       namespace: portworx
     patch: |-
       - op: replace
         path: /metadata/name
         value: example-todo-app
       - op: replace
         path: /metadata/name
         value: example-todo-app
       - op: replace
         path: /spec/template/spec/namespaces
         value:
           - example-todo-app
