apiVersion: v1
kind: Secret
metadata:
    name: cluster-key
    namespace: openshift-gitops
data:
    sops.asc: ENC[AES256_GCM,data:2gOac1nDKZyLYuF45EbKXZaXSjLThWhmGOz/dP9vGe4qkb9g0oLOWlByh6nHCZZZ2SK8Nsq0adU9uCTxj5z7ec+OMpba/6en9ARGmx/0KXD2/+gt75ZN0D+lXZxA3ow9ajk7l6qk1gFL51kzuJiIkUJZRnHYIkTW5SwNMDGQB6oz7pIYXn4M08qGQh8gbgnktNNyYGAWT+UYAGwU6yU36Fa+CkemPi4nj+pjCXZtfpnnrFZQwLQy/MwnPZxj1j7mOPRreUy1e8V0w77AwnMP3AAm/6lbDf95YRAGkdACouAEyRTfrZFebJAuGbY1ZXKWzj8cfiSavuAUQDvfUnX0YiTjrovwMi/HjRoq/n5LHc6uaPfhN8lTvyJg1LJm71eXli4pJCB4Ln+ocw0MKuxM45GjPrtnmAH7l0Qqm1dRjgj19CewxImdnF2zxiFDcNsZ643r2p1A3BLgMQ0EsBzEdhCS5Mq2eforvdZB1v2ZAqxF2rpxZkFlNya8jGPamtkyKzu0AXKsymYTqYNsRPyObeCeBte7wS7MlxEQzUIa0Py9oH7TXECIhCyvZqqvboz7Ti8QWn/OaUTf7YFJc1LP5fOQyvo/go1XtHZjAuiMGyZrUfaualbLGeUWMhw/rjIuE1Fm8oTbpJEuBo1UfAu4I6hXoSqp3oTx+wok+4dlYnSPLxTr/A+uXvXZB8iyWGwGiQw6a7Pg69VTpTiBZVd1D7A4pfq79nbx/MN3ayQwJW65A6G2T/BlNSJWioStDLZnoGWBOluvI3BDYomCHJ0B5qBhZFGYWvKRp84yfp9yxsPklUBuV3xldmqOKlshtQRzMG0c5v093NCDf7bEOLjrCdLywF9q5ZvmXG6Qu1xLfLVw4vkaXOIMJQzQ3oV+iAl4fgeGgnjbaps+Gr6WKz5ZyXZoqnBqvZ1aRbiwEJbEjiBhHPEZTvgSCWW+L5AcbGjtdwzmGAx2QLJbcDfo5dMyfWBnlKmgF102sl4h1oS5lOOCbXYCsVf0m6j6nQcDlmnlgjL9xEoAVx6XgqG9vuJV9dZgqlf+hl1oKj2TW8ixlV/J0yki4TfrHK4+hNDusRYwbN0LRH4Kscyuh2PzEd2x0VP6xv691hKvOlDIjI6dV8dOYFjGrup8xO908aAh+UqL4OeH8rpfb2RQE9U1tNC6CApvN+8Y2NQoQBloQP8i1MxXgkAHHNO+XDDOF84CQb7sOtGqoAAQdt8x13+2M5m4h7ABnXVa3Lzg3reTckcUJ/RawKKnM+SUQI2QUtNepj8kEY4ZwI7pJ0Ndobo8qhdSgMQiKCs=,iv:8CU9l1ULq2SUICt8T8gMgK/KvZBjiR+rniRrr7RSxUg=,tag:iHjY5imJT26xJGYgxqzmTA==,type:str]
sops:
    lastmodified: "2025-11-22T00:21:29Z"
    mac: ENC[AES256_GCM,data:hCWoFvTSLWaiQacWLyQtuckdicZfn5gwI15e+6eSvOWr0GeE+H/U6bRMgz6nOPPBVOCUogEza6IBVdOjJg7UQ+cQQSwWnO//W4vmFUVoPfgyAss0HkhY84OLiMnC5MltJbjPFnZJrDP/WFNtITtw1tSeKGPvavBSWIBuZvFViBw=,iv:3Ov66+V1OqvtxyOBwF3oIqa5PRIIN8TYmwcpuVJ2PS0=,tag:VziMLWNoy9Yui7PN2qfwPg==,type:str]
    pgp:
        - created_at: "2025-11-22T00:21:29Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DeXeC3vKOE18SAQdAtgYTrtujepOrvRvEYtx2/zbT9AQyfPmX28cfBSP5/x8w
            OiFIQhYYFle+t1PT3nEW17gM4G1sMlQyXHfb5qdC96ZCcPjWCAV6LxHYgGdRezue
            0lwBWNxl06qzPRkGqMOUHF6NZ+PVwaFzl6Miu+kVvi7nqXT6FIe+426vdGYMn0x/
            PF9qwPh7RqLfZn2/GeWLSITp7nGZKhVAbbjGVxcOqQbm4MKyVA03I7exQlvVPQ==
            =/gcA
            -----END PGP MESSAGE-----
          fp: 690EB362BCE71D5794727EF0382DB86937BB1D2F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
