apiVersion: v1
kind: Secret
metadata:
    name: cluster-key
    namespace: openshift-gitops
data:
    sops.asc: ENC[AES256_GCM,data:n11hQisJJXKWxa+7RsXXMDpafucfoa1NmhcmW8c50aQdfcKrCFgB3KkoJwC6nqRK48pDs7vWkB44Fp5X0IuaFF7hkuwY/FDxniqrcPFyOgb+CpotHP94tsYZctr9Emm5RQu0ovl9jBDSCOABpkq3RXTuEImM03Q1dFasydUsYuTsfvOjUF2vML0ACxTti0L1wdghz+sD4jEDxQfy9bTw3Odb9LUonpGUPTRQs9AYXxZArhOj0UDKXNIIqn1u/HstoVyP38C55r8B1r6WspNSnDY1vu6SQqReVZK+0zco9dL86oXBPRtF4nCmTNAZ77thkaTGImDLJi84+lAXfyKgh7pEacD01SltXzAw/xjAeJsA9422OLKVNVlJCjPdVYQmQ7S+79UWSWhg1YdDZDe0Q1Kql6fioGjjh/fJ8G5320XUuPnt5x6pk4ROA3IfT/SP0YRO65qwRKvKgLdJfwHiHwWATpanvIAJ3Xf8rCKagf5PFzyX2Me/oWL2xlfNPz0IET7m6WEtzptxLle6Al0REXGLBBnBctw4Iu1vgq4DiOGh9qPJFBwXGt/yP8gY+6iXqaOViCHcfFCXzuSbTCCFcutNGwI2CYA++Y5zlG4Z3HjvuQ1XDfLU+oFnrnzNp6iML7Ly4kJHY8Tysp4kzkGOR12WjBC26bnwrisdaCAZJhg1Gc0d3l+J+hjZqE2cVx3/c+IA0Bxt0YEbOrO0PftgiSnJ0+ukalTELebKmpz0jb1DkUS/FJQG4sh30mYHZQCh3cd0vk7X4XSESOHw+UlnEGtkhLexUA+oKRyOMYAIVjXTNlCwNPgo8riLvD03mxfkE19+KDY5goMK+KCQjuuc98hLmoEJnx91kaxqFIoTlWoz0DC+ONMT6QI+KlE5RAZbA83+kp5J+y8xXNCX4/A9wMijDEIohhiwqqshCl5SwCIuAx9rmaaQ4qlUoNOFhTr1NL15p4BoHo9DC2UIxK0DrJbCsGqEbIt5iHKRNlmmUJx4m4DWLxgDcHD7y4u6LMIyNgv4kCIft9iAExmXfFOHCOUOJgONgZZATWybHD8A/ucqRZ9RNFQRvuZccvPMDUvhDNz3yYY3+nkv5q8X1g2eqcx6CyY8dErS95Eyl1ZSvDoHCXW6uxNF7g8OYdU0Gm2/jz6xwG8nv5SKo7c9o+vm5CJAhpHI+SIL+71BVD7229YWTyihFf2DUpp5bdFqv8enUStwPjN+RKH00KTufQESuxDzQ3wN/7coY/T6tEjM/S1fJMGnzYiilykGXy95XGajU/D+m8uz0c3CuMISFFoGswtXm98=,iv:nLZSiaHxt6O+W2azgz3mWsjC5GrFFUBeTlgs2Ermpcg=,tag:y4o059EsQ0K9yqMDWQx4og==,type:str]
sops:
    lastmodified: "2025-11-22T00:01:23Z"
    mac: ENC[AES256_GCM,data:imX/jxvMboE2dxDVofPeYZA3sjyVp3Px0oUnRWIregkw+bFc9ecNnmt8AhS1tG7GqampoyPjMlSVzMMLCVFoFeBZJJJ2HzFuNYmkixQrpmJA2YXEd4uQNBbaZ50+vn66l5fk88CD+s1F0R4vz9PU66qUPBQ0QEDo3kSDSDd2fCQ=,iv:kfWfdt2SwbFfZMDiuc7TvJDU3k4WrTwFuI6wXcP23gA=,tag:iLCQmxTfMloemPmjmkd0dA==,type:str]
    pgp:
        - created_at: "2025-11-22T00:01:23Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DeXeC3vKOE18SAQdA8CrR3WajskqQsJq8RP+AcZPn0wuWJ+lhIBrFwYmApkEw
            x4wnZWqv8OKuyC7ynfHsEeIpNSvQ+hQTlIQ0a9pGo0pYYFMMknHUpHHardCP8SL1
            0l4BXFctf+Hm39baCugQVocPsE0B1+0BhheM0qjVLjnD69mepiGyByDSPJKrQz1P
            fguBfUxk0RdkX0tRtsEVSn1HTiasbNwBhjAqr+UrZfAohNGpy0SAJe31yKBg7K2B
            =nIB2
            -----END PGP MESSAGE-----
          fp: 690EB362BCE71D5794727EF0382DB86937BB1D2F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
