apiVersion: v1
kind: Secret
metadata:
    name: cluster-key
    namespace: openshift-gitops
data:
    sops.asc: ENC[AES256_GCM,data:QHksA+TWWubD+KtZUwxgjc1jtYg4mmIc7QQGR78F4dS7/tWWUZ2HAPNOQNOCvcs4zerAkBd6MEuvf6P8kl0wBy+qkwfEwg8/3dyi8wZMdZD/KoyeVPvI/HM8ZgNApdq4DtB6SMG+xy6YmuF2jzkbX24ru1oVGWUv7NzrjL9kYkG7b4Rm/9ud9kUF/sDpTkDoD1/OguFm2/iFYQzw8CBsRQ7qxQbSeUg1G1s5RJGG751upw2TQGnEmcg8foNvnSM3R8eOtoFAM50Bb5M4zKNmyNtX42Z/9muyVfbY9iY/M7uQ//Tp7rw+RzuxR6k70Z/aJly78h/dvqrbyPH3kwWp7yHZZuZ7Lo7itZ08mDYCQtRNqXteDD09LVq9Ql0dzPmrWyIZx/0r5quTY6c7Gupi0748HTVXYzWMehdU8YUjZ24g6QgINScune47zzTRqZ9LmEYb1enTfDb9i11usOyDU3h5kwlzqZwsTKUeLZvzul/KDG0A9puQJO3l+31SeaU0juUW18qpnZPQe1SozcIPKQKTW4Tg+GuVbpNibRYMRlOtd1wx4DFd93KbJGhZon/8rqt10KItJVDlrsJdvHIzSH5gxULwURVLacfROxXQotATur150JL2jqUvboOeFO/DgyAWSIHxAL2PTKKLTj+PQ3oDPLHLLwrz/hSvap8L2Hpfjv08gVsGdzKTk2+cUhIyulPsqb6xVYLHlpxk3TYYOdhbwyqE5/ZJzBtjG8QujwOuiynBEV1ZItJX8Gkg4aTtT+fB9oEiNTtkAn5cZU1G3lGCO0pgOUIi1fbdoWg3m4lWdkWYq0O2QwJ9A7YBSMjuoAJSLRUH0oEiHk+ZQJuRTXsHyzIAruI270XMoaO1b1KXL+nobr1xqX3zhfUslrsQHjTX+AsSGbtXMamEXH0Ge5Mt2elt+gvg6iFgaCw1jMknoiXPStPeCv7m98vrm8kp6JMY78SRHUcZIEwCYTZxMezCg0oqtstGQiDMfghCsrdYCQTU5hDvwIp9EJeRdLd/KFEZdqpoc499O7igmN69RS3nl+rAETFuDZRCEsjwy9PE+T7oI0SQ0x4lsf7YC6wz8TvXD5Sw2QnGKBtA9f/QcCfaUY4lRsdhvyMuZpjFG9Y0kV9ybsyt/dJojJMLn0hlScazwRVTjrVic8MLwSJiE/jfRH0wKb9IeHdJfdLD5AhCIei68Y4o3rWzxSHQkuw/HhboR3FNDoqjg1pXs50lAd4iF1qPcLvJEj2ZaheKiTJ/tCmo1xnBmgSQVtBzKbSxKA9tk+azx9YRKVLOke/1SO4v8EU=,iv:79DUXCrA5nvH9rwjhmnvLaPRidW86qTCJOh6mOiwb74=,tag:DktCI1qcKtKcHdfFCPSlWw==,type:str]
sops:
    lastmodified: "2025-11-24T19:45:09Z"
    mac: ENC[AES256_GCM,data:p5EMIzUmypFBX6FMgX2Ba1AxYxyJ2LYQbnMu+GdYrE6jo9Ew78WhgZUauN7ueiIJAqH61kM370UUgxYZPAlHBmKlHkLRVyZ91YQ5+3pw5sqPg4fJEOpXE6onN3GzyfCFUyrmTYUEsPo9LFVpm4LIBHQ4LRjM8UeAaUbXmRGqFQs=,iv:8BPPqYt8t9DOL0wz02ZJWZDePecXrYKciVVGsx+sD4E=,tag:5NoJYn9Xw/vSWyNYKY0tSw==,type:str]
    pgp:
        - created_at: "2025-11-24T19:45:09Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DeXeC3vKOE18SAQdAhcmBnci3x/vI6XMQw8VSAjIDHqVtEL+rv1iul75gFGow
            CP+4r7sn8KUesBZnY+mkRZQ6QxSfX0vh8PHiyfOCe1vOn1vLQG/joGoSTMKTUIhl
            0lwBWiMIK9k3zXLQj02QT5RDzRTIfbhk6pvxZyj3ThRmaUBBd86r3OP4GuG5PKRh
            acxoyEIW/9uF9iNCa9TPlRoMdAvQ+5Qp+0NACpbPBipI1MY1qZiAl4+RiXc6hw==
            =Bb+M
            -----END PGP MESSAGE-----
          fp: 690EB362BCE71D5794727EF0382DB86937BB1D2F
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
