apiVersion: v1
kind: ConfigMap
metadata:
  name: sops-config
  namespace: openshift-gitops
labels:
  cluster.open-cluster-management.io/backup: ""
data:
  .sops.yaml: |-
    ---
    creation_rules
    - path_regex: '.*.yaml'
      encrypted_regex: '^(data|stringData)$'
      pgp: {{ cluster_key_fp }}
