kind: StorageCluster
apiVersion: core.libopenstorage.org/v1
metadata:
  name: replace-me
  namespace: portworx
  annotations:
    portworx.io/is-openshift: "true"
    portworx.io/service-type: "portworx-api:LoadBalancer"
spec:
  image: portworx/oci-monitor:3.4.1
  imagePullPolicy: Always
  kvdb:
    internal: true
  cloudStorage:
    provider: gce
    deviceSpecs:
    - type=pd-balanced,size=150
    - type=pd-balanced,size=150
    - type=pd-balanced,size=150
  secretsProvider: k8s
  startPort: 17001
  stork:
    enabled: true
    args:
      webhook-controller: "true"
  runtimeOptions:
    default-io-profile: "6"
  csi:
    enabled: true
  monitoring:
    telemetry:
      enabled: true
    prometheus:
      exportMetrics: true
  volumes:
    - name: cloud-creds
      mountPath: /secrets/cloud
      secret:
        secretName: cloud-creds
  env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /secrets/cloud/osServiceAccount.json
    - name: SAAS_ACCOUNT_KEY_STRING
      valueFrom:
        secretKeyRef:
          name: portworx-saas-key
          key: saas_key
